// ============================================================
// siteData.ts — AUTO-GENERATED by site_generator.py
// Do not edit manually. Re-run the generator to update.
// ============================================================

export type Variant = 'A' | 'B' | 'C' | 'D'

export interface ServiceItem {
  iconName: string
  name: string
  description: string
}

export interface ReviewItem {
  name: string
  rating: number
  text: string
  date: string
}

export interface WhyUsPoint {
  heading: string
  body: string
}

export interface ProcessStep {
  heading: string
  body: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface SiteData {
  businessName: string
  instagramUrl?: string
  facebookUrl?: string
  trade: string
  tagline: string
  phone: string
  email: string
  address: string
  city: string
  serviceArea: string
  googleBusinessUrl: string
  yearsExperience: number
  bookingUrl?: string
  logoUrl?: string
  photos: string[]
  variant: Variant
  hero: {
    heading: string
    subheading: string
    primaryCta: string
    secondaryCta: string
  }
  services: ServiceItem[]
  trustItems: string[]
  whyUs: {
    heading: string
    subheading: string
    points: WhyUsPoint[]
  }
  process: ProcessStep[]
  faqs: FAQItem[]
  about: {
    heading: string
    body: string
    ownerName: string
  }
  reviews: ReviewItem[]
  seo: {
    title: string
    description: string
    canonicalUrl: string
  }
}

const siteData: SiteData = {
  businessName: 'Strandek Flat Roofing Bristol',
  trade: 'Roofers',
  tagline: 'Bristol\'s Trusted Flat Roofing Specialists',
  phone: '+44 117 290 0050',
  email: 'info@strandekflatroofingbristol.co.uk',
  address: 'Newminster House, 27-29 Baldwin St, Bristol BS1 1LT, United Kingdom',
  city: 'Bristol',
  serviceArea: 'Bristol',
  googleBusinessUrl: 'https://www.google.com/maps/search/?api=1&query=Strandek%20Flat%20Roofing%20Bristol&query_place_id=ChIJ2zuPgyyPcUgRUF44ANSoRes',
  instagramUrl: 'https://www.instagram.com/aiwithdennis',
  facebookUrl: 'https://www.facebook.com/leadplug/',
  yearsExperience: 50,
  logoUrl: 'https://www.strandekflatroofingbristol.co.uk/wp-content/uploads/2023/02/strandek-favicon-2.png',
  photos: ["https://www.strandekflatroofingbristol.co.uk/wp-content/uploads/2021/09/Built-GRP-Fibreglass-Roofing-System-with-skylight.jpg", "https://www.strandekflatroofingbristol.co.uk/wp-content/uploads/2022/01/flat-roof-repairs-in-bristol.jpg", "https://www.strandekflatroofingbristol.co.uk/wp-content/uploads/2021/09/Built-GRP-Fibreglass-Roofing-Bristol-e1651574773666.jpg"],

  variant: 'A',

  hero: {
    heading: 'Expert Flat Roofing Services in Bristol',
    subheading: 'Professional roofers serving Bristol and surrounding areas with reliable flat roofing solutions. Fully insured with 5-star Google rating for quality workmanship you can trust.',
    primaryCta: 'Get a Free Quote',
    secondaryCta: 'Call Now',
  },

  services: [
    {
      iconName: 'Roof',
      name: 'Flat Roof Installation',
      description: 'Complete new flat roof installations using high-quality materials and proven techniques. We handle everything from residential extensions to commercial buildings with precision and care.',
    },
    {
      iconName: 'RefreshCw',
      name: 'Flat Roof Repairs',
      description: 'Quick and effective repairs for leaks, cracks, and weather damage on all types of flat roofing. Our experienced team identifies the root cause and provides lasting solutions.',
    },
    {
      iconName: 'Shield',
      name: 'Roof Waterproofing',
      description: 'Professional waterproofing services to protect your property from water damage and leaks. We use advanced materials and techniques to ensure your roof stays watertight.',
    },
    {
      iconName: 'Search',
      name: 'Roof Inspections',
      description: 'Thorough roof inspections to identify potential problems before they become costly repairs. We provide detailed reports with clear recommendations for any necessary work.',
    },
    {
      iconName: 'Hammer',
      name: 'Emergency Roof Repairs',
      description: 'Fast response emergency repairs for urgent roofing problems that can\'t wait. Available for storm damage, sudden leaks, and other roofing emergencies across Bristol.',
    },
    {
      iconName: 'Home',
      name: 'Roof Maintenance',
      description: 'Regular maintenance services to extend the life of your flat roof and prevent costly problems. We keep your roof in excellent condition with scheduled inspections and upkeep.',
    },
  ],

  trustItems: [
    'Fully Insured',
    'Free Quotes',
    'Local to Bristol',
    '5-Star Google Rating'
  ],

  whyUs: {
    heading: 'Why Choose Strandek Flat Roofing Bristol?',
    subheading: 'We\'re Bristol\'s trusted flat roofing specialists, committed to delivering quality workmanship and excellent customer service on every project.',
    points: [
      {
        heading: 'Local Expertise',
        body: 'Based in Bristol, we understand the local climate and building requirements. Our knowledge of the area means we can recommend the best solutions for your specific needs.',
      },
      {
        heading: 'Quality Materials',
        body: 'We only use premium roofing materials from trusted suppliers to ensure lasting results. Every job is completed to the highest standards with attention to detail.',
      },
      {
        heading: 'Fully Insured',
        body: 'Complete peace of mind with full public liability insurance coverage. You can trust us to work safely and professionally on your property.',
      },
      {
        heading: '5-Star Service',
        body: 'Our customers rate us 5 stars on Google because we deliver on our promises. We take pride in exceeding expectations on every project.',
      },
    ],
  },

  process: [
    {
      heading: 'Contact Our Team',
      body: 'Get in touch by phone or email for a friendly chat about your roofing needs. We\'ll arrange a convenient time to visit your property.',
    },
    {
      heading: 'Free Survey',
      body: 'Our experienced roofers will inspect your roof and discuss the best options with you. We\'ll provide a detailed written quote with no hidden costs.',
    },
    {
      heading: 'Professional Work',
      body: 'Once you\'re happy to proceed, we\'ll complete the work efficiently and to the highest standards. We keep disruption to a minimum and clean up thoroughly.',
    },
    {
      heading: 'Quality Guarantee',
      body: 'We stand behind our work with a comprehensive guarantee for your peace of mind. Our aftercare service ensures you\'re completely satisfied with the results.',
    },
  ],

  faqs: [
    {
      question: 'How long does flat roof installation take?',
      answer: 'Most flat roof installations are completed within 1-3 days, depending on the size and complexity of the project. We\'ll give you a clear timeframe when we provide your quote.',
    },
    {
      question: 'Do you work in all weather conditions?',
      answer: 'We prioritise safety and quality, so we don\'t work in heavy rain or strong winds. We\'ll reschedule if weather conditions aren\'t suitable for roofing work.',
    },
    {
      question: 'What types of flat roofing materials do you use?',
      answer: 'We work with all modern flat roofing systems including EPDM rubber, fibreglass (GRP), and felt roofing. We\'ll recommend the best option based on your budget and requirements.',
    },
    {
      question: 'Can you repair my existing flat roof?',
      answer: 'Yes, we handle all types of flat roof repairs from small leaks to major damage. Our team will assess the condition and advise whether repair or replacement is the most cost-effective option.',
    },
    {
      question: 'Do you provide emergency roofing services?',
      answer: 'We offer emergency repairs for urgent problems that can\'t wait. Contact us immediately if you have storm damage, sudden leaks, or other roofing emergencies.',
    },
    {
      question: 'How much does flat roofing work cost?',
      answer: 'Costs vary depending on the size, materials, and complexity of the work. We provide detailed written quotes with no hidden charges, so you\'ll know exactly what to expect.',
    },
  ],

  about: {
    heading: 'About Strandek Flat Roofing Bristol',
    body: 'I\'m passionate about providing Bristol homeowners and businesses with reliable flat roofing solutions that stand the test of time. Having worked extensively across Bristol and the surrounding areas, I understand the unique challenges our local climate presents and take pride in delivering workmanship that protects your property for the long term. Every customer deserves honest advice, quality materials, and professional service, which is why I\'m committed to building lasting relationships based on trust and excellent results.',
    ownerName: 'The Strandek Team — Owner',
  },

  reviews: [
    {
      name: 'Elizabeth L.',
      rating: 5,
      text: 'Thank you very much for your professional work. Your team were excellent from the initial roof survey and helped us deal with an insurance claim for a flat roof repair.',
      date: '',
    },
    {
      name: 'Pat W.',
      rating: 5,
      text: 'Excellent job, thank you!\nStrandek were professional and very helpful at each stage of the process of re roofing my attic conversion flat roof.Survey and quote completed promptly, work explained and all finished to a very high standard in the 2 days when they came. Would highly recommend their service.',
      date: '',
    },
    {
      name: 'Ben L.',
      rating: 5,
      text: 'The team were professional and efficient, did a great job and cleaned up the site afterwards. Would definitely recommend',
      date: '',
    },
    {
      name: 'Andrew C.',
      rating: 5,
      text: 'The team worked in a difficult period of weather to deliver a garage roof that has held up well to a couple of storms. I am very pleased.',
      date: '',
    },
  ],

  seo: {
    title: 'Strandek Flat Roofing Bristol | Roofers in Bristol',
    description: 'Expert flat roofing services in Bristol. Professional roofers offering installation, repairs & maintenance. Fully insured, 5-star rated. Call 0117 290 0050.',
    canonicalUrl: 'https://preview-strandek-flat-roofing-bristol.vercel.app',
  },
}

export default siteData

// CSS custom properties injected by site_generator.py
// These override :root variables in index.css at runtime
export const siteTheme = {
  '--color-primary':  '#1C1C1E',
  '--color-accent':   '#E85D26',
  '--color-bg':       '#F9F9F9',
  '--color-text':     '#1A1A1A',
  '--color-muted':    '#6B7280',
  '--color-border':   '#E4E4E4',
  '--font-heading':   "'Instrument Serif', Georgia, serif",
  '--font-body':      "'DM Sans', system-ui, sans-serif",
}
